### ISSUE TITLE
Apple Match-O Linker (Id) Errro

### ISSUE THREAD

**Issue by PaulRBerg** [malczak/VideoCaptureOverlay#1]
When I try to run the project, I get this:

```
ld: library not found for -lPods
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I've made sure I've installed the pods by `pod install` and opened the xcworkspace.

**Comment by malczak** [comment]
Remove `Pods` dependency and add `libPods-VideoCaptureOverlay`
